page:
  title: Timelinetool
  url: http://timelinetool.com
  description: This is the timelinetool
  keywords: timeline,timelinetool
  author: Hauke Schade's Timelinetool

# the default language to use, timelines however can specify different languages
language: de

paths:
  public: public
  migrations: app/migrations
  smarty:
    cache: app/cache
    compile: app/compile
  storage: app/storage

permissions:
  scope: timelinetool
  admin: admin
  edit_timeline: edit_timeline

authserver:
  host: localhost
  scriptpath: ''
  port: 80
